//
//  Database.swift
//  ARSneakers
//
//  Created by Ahmad Qureshi on 19/05/22.
//

import Foundation
struct DataBase {
    static var shared = DataBase()
    var allData = [
        DataBaseModel(resourceName: "AirJordan1BlackHigh", companyName: "Nike", productModel: "Nike Air Jordan 1 Black High", productDescription: "Crafted from black and white leather, the Air Jordan 1 High OG twist from Jordan are ready to help you shoot and score. Alley-op. Featuring a round toe, a lace fastening, a flat rubber sole and a signature Nike swoosh.", productPrice: "₹15999.00"),
        DataBaseModel(resourceName: "AirJordanRetroHigh", companyName: "Nike", productModel: "Nike Jordan Retro High", productDescription: "Familiar but always fresh, the iconic Air Jordan 1 is remastered for today's sneakerhead culture. This Retro High OG version goes all in with premium leather, comfortable cushioning and classic design details.", productPrice: "₹13,995.00"),
        DataBaseModel(resourceName: "ConverseGolfBlackGoldSneakers", companyName: "ConverseGolf", productModel: "Converse Golf Gold", productDescription: "The Golf Le Fleur x Converse Chuck 70 Hi “Pink Flames” is a collaboration between Tyler, the Creator and Converse on the retro-infused high-top lifestyle shoe. The pair features a light yellow colourway that features flames graphics inspired by the clothing and accessories released by Tyler, the Creator’s Golf Wang clothing brand during the mid-2010s 'Cherry Bomb' era. A pink Converse Chuck 70 license plate on the heel of the cream vulcanized rubber midsole completes the look.", productPrice: "₹7999.00"),
        DataBaseModel(resourceName: "NIikeReactPresto", companyName: "Nike", productModel: "Nike React presto", productDescription: "A new take on the original Presto, the Nike React Presto features a revamped design and new technology. They have a stretchy fabric upper, slip-on construction, React technology, TPU cage, and a rubber outsole.", productPrice: "₹9999.00"),
        DataBaseModel(resourceName: "Nike_Air_Mag", companyName: "Nike", productModel: "Nike Air Mag Premium", productDescription: "The Nike MAG is a limited-edition shoe created by Nike Inc. ... It is a replica of a shoe featured in the film Back to the Future Part II.The shoes feature an electroluminescent out-sole, space age materials, and a rechargeable internal battery good for 3,000 hours. They are the first rechargeable pair of footwear made by Nike.", productPrice: "₹108000.00"),
        DataBaseModel(resourceName: "Nike_Jordan_Air_Max", companyName: "Nike", productModel: "Nike Air Jordan Max", productDescription: "Russell Westbrook is fast. These shoes match his quickness with updated cushioning, data-informed traction and a full-foot fit system to keep him in control. With a rugged utility look combined with a purposeful clash of colours and materials, this model speaks to the core of Russel's  Not? mantra.", productPrice: "₹12400.00"),
        DataBaseModel(resourceName: "AdidasHighSport", companyName: "Adidas", productModel: "Adidas High Sport", productDescription: "Your passion, perspective and ideas are all part of what makes you unique. As you find your own creativity and self-expression, these adidas shoes weave primary and pastel hues into every stride. When you share your voice with others, you create opportunities to strengthen your community. The Trefoil serves as a reminder of the power of coming together.", productPrice: "₹5399.00"),
            DataBaseModel(resourceName: "AdidasYouthAlphaSkin", companyName: "Adidas", productModel: "Adidas Youth Alpha Skin", productDescription: "our confidence consumes your opponents. Your vision leaves them with nowhere to hide. Seize your unfair advantage and take control in these juniors' adidas Predator", productPrice: "₹6499.50"),
            DataBaseModel(resourceName: "AirForce", companyName: "Nike", productModel: "Nike Air Force 1", productDescription: "The Nike Air Force 1 ’07 WW is the b-ball OG with the look you know best: crisp leather, bold colours and the perfect amount of flash to make you shine. Featuring Nike Worldwide graphics throughout, it lets you celebrate the unity of sport in legendary style.", productPrice: "₹7,495.00"),
        DataBaseModel(resourceName: "NikeAirJordan1Red", companyName: "Nike", productModel: "Nike Air Jordan 1 Red", productDescription: "Supplied by a premier sneaker marketplace dealing with unworn, already sold out, in demand rarities. Each product is rigorously inspected by experienced experts guaranteeing authenticity. If you're an avid sneakerhead, chances are you won't want to pass up on these. Crafted from black and white leather, the Air Jordan 1 High OG twist from Jordan are ready to help you shoot and score. Alley-op. Featuring a round toe, a lace fastening, a flat rubber sole and a signature Nike swoosh.", productPrice: "₹14999.00"),
        DataBaseModel(resourceName: "NikeEastK75LowPolyFreebie", companyName: "Nike", productModel: "Nike East K75 Low", productDescription: "Nike is one of the leading manufacturer and supplier of sports equipment, footwear and apparels. Nike is a global brand and it continuously creates products using high technology and design innovation. Nike has a vast collection of sports shoes. You can explore our range of basketball shoes, football shoes, cricket shoes, tennis shoes, running shoes, daily shoes or lifestyle shoes. Designed for top performance, these shoes match the way you play or run. Available in materials like leather, canvas, suede leather, faux leather, mesh etc, these shoes are lightweight, comfortable, sturdy and extremely sporty. The sole of all Nike shoes is designed to provide an increased amount of comfort and the material is good enough to provide an improved fit. These shoes are easy to maintain and last for a really long time given to their durability.", productPrice: "₹24999.00"),
        DataBaseModel(resourceName: "NikeVOC", companyName: "Nike", productModel: "Nike VOC", productDescription: "he company's VoC operation is a collaboration between several teams, including customer support, digital operations, digital product", productPrice: "₹4999.00"),
        DataBaseModel(resourceName: "RedTapLeatherShoe", companyName: "RedTape", productModel: "Red Tape Militiary Leather", productDescription: "Depicting finesse in the art of shoemaking, this Tan coloured brogue shoes from Red Tape is one of its kind. In addition to its stunning broguing, this pair has been given a pvc sole finish and a leather upper Mat to ensure you of the comfort level. Sturdy yet stylish, this smart pair of scottish origin shoes can be worn across any casual or formal event.", productPrice: "₹4999.00"),
        DataBaseModel(resourceName: "ReebokCrossfitNanoShoe", companyName: "Reebok", productModel: "Reebok Crossfit", productDescription: "From boot camp in the park to bodyweight exercises at the campground, these men's Reebok training shoes take you out of your routine and help make fitness fun wherever you are. Floatride Energy Foam in the forefoot gives you a lightweight feel and responsive ride. Raised lugs for better traction on any surface.", productPrice: "₹12999.00"),
        DataBaseModel(resourceName: "ReebokPumpPlus", companyName: "Reebok", productModel: "Reebok Pump Plus", productDescription: "You don't break the rules. You make the rules. So write your own destiny in these men's Instapump Fury Zone shoes. Ditch the laces, pump them up and adjust the strap to wear them your way. A TPU insert on the midsole and a fierce outsole tread based on the original shank amp up your look", productPrice: "₹15699.00"),
        DataBaseModel(resourceName: "VansRedWine", companyName: "Vans", productModel: "Vans Red Wine", productDescription: "Reebok Men's Pump Plus Tech Solar Yellow and Black Running Shoes", productPrice: "₹7899.00")
    ]
    
    
    var favData : [DataBaseModel] {
        allData.filter { $0.isFavourite == true }
    }
    var cartData : [DataBaseModel] {
        get {
            allData.filter { $0.addedToCart == true }
        }
    }
}
